feat: add tree-shakability and update project structure
phosphor-icons/vue pull request #14
Opened 2022-01-23 22:51 UTC by dnlsndr

This commit add tree-shakability so that one can import only the icons that one needs.
Due to some other improvements and general standards, the project structure has changed
a tiny bit.

fixes #10

2022-01-24 11:25 UTC, dnlsndr commented
Seems like there is still an issue i need to fix. Damn, it's not as easy as it seems. The library is now compiled to esmodules, but it still seems as if it's not tree-shakable. Will have to do some more research.

2022-01-24 11:41 UTC, dnlsndr commented
For anybody interested, here's a good resource on what's the issue at hand (mainly compiling with rollup, and tree-shaking with webpack as already stated in a different issue): https://blog.theodo.com/2021/04/library-tree-shaking/

2022-01-24 14:50 UTC, dnlsndr commented
@rektdeckard I've fixed some final issues here. I created a package of this repo to test it in our local setups under `@dnlsndr/vue-phosphor-icons` and it works pretty well.

2022-01-24 17:41 UTC, rektdeckard commented
Thanks for putting the work in @dnlsndr. Please run the formatting script to eliminate all these single quotes and properly indent all the generated code. I'll give this a test later tonight!

2022-01-24 17:48 UTC, rektdeckard commented
For future ref, you can use the `example` demo app to test the bundled lib in a demo app immediately, or `npm link` command to text in an existing local project, without having to gum up the npm public registry with random test modules.

2022-01-24 19:53 UTC, dnlsndr commented
@rektdeckard Yeah sorry about that. I do have an issue with using the example app, because it only uses the source files instead of testing the production output, so it's not really representative of what you may get in the end after building the library, especially when testing for tree-shakability. One could of coure just do a `npm pack` for testing but one wouldn't want to gunk up the repo with yet another special configuration in the `package.json`. I'm also not in favor of needlessly publishing packages to `npm`, but since we ourselves also needed a quick fix, I had to publish the fixed version of the package anyways for our deployments to reference. Maybe one could add a `CONTRIBUTING` guide so that anybody who wants to fix something with the library knows exactly what they need to do (including running the format script). I'd be glad to help out with this repo in any way possible, since as I already mentioned, we do also heavily rely on Phosphor icons at work and thus also want to ensure that the library meets general standards.

2022-01-24 20:22 UTC, dnlsndr commented
I've reverted several needless formatting changes.

2022-01-25 12:58 UTC, dnlsndr commented
I think it should be ready for review now

2022-01-29 22:08 UTC, rektdeckard commented
Taking a look now!

2022-01-30 01:38 UTC, rektdeckard commented on bin/assemble.js
> +    console.log(chalk.green("Export success"));
```suggestion
    console.log(chalk.green("Typegen success"));
```

2022-01-30 01:40 UTC, rektdeckard requested changes

2022-01-30 01:40 UTC, rektdeckard commented on package.json
>    "unpkg": "dist/vue-phosphor-icons.min.js",
```suggestion
  "unpkg": "dist/phosphor-vue.min.js",
```

2022-01-30 01:41 UTC, dnlsndr commented on package.json
>    "unpkg": "dist/vue-phosphor-icons.min.js",
Don't know how that slipped in there

2022-01-30 01:56 UTC, rektdeckard commented
nit: keep commit titles to 80 chars or move rest to description

2022-01-30 02:47 UTC, rektdeckard commented
Works a charm, thanks @dnlsndr

2022-01-30 02:48 UTC, merged

2022-01-30 03:19 UTC, rektdeckard commented
@dnlsndr Actually, reverting because it's incorrect to export the component types as a `.ts` file. We should emit ambient declarations in a `.d.st` file using `export declare` syntax, in the way that Definitely Typed would do.

2022-01-30 08:19 UTC, dnlsndr commented
I'll have a look