Migrate from rollup to vite
phosphor-icons/vue pull request #22
Opened 2022-05-06 07:35 UTC by micksi

- minimal solution
- support tree shaking
- umd build instead of cjs and iife
- TODO: check ssr usage is still working

2022-05-20 16:18 UTC, philefstat commented
This worked great for me 👍 Thanks very much. My bundle size went down by ~80% 😅

2022-05-22 05:48 UTC, xeonicca commented
how do I use this branch as a replacement for the time being? thank you

2022-05-30 13:14 UTC, micksi commented
@rektdeckard can you give this PR some love 😊 To not break existing setups the package should probably be released as a 2.0 release

2022-11-13 01:38 UTC, dacohen commented
We tried to include phosphor-vue in our Vue3/Vite project, and besides generating a massive bundle, the build process was consuming almost 4 GB of memory, causing our CI/CD to crash.

This PR appears to solve both of these problems. Is there a specific reason why this hasn't been merged yet?

2023-01-07 20:32 UTC, rektdeckard commented
Hey @micksi, @philefstat, @dacohen and everyone else watching here. Apologies for the total disregard to your very real concern about bundle size and tree-shaking. I'll be reviewing and testing this today, hope to be able to push this live soon alongside a slew of other 2.0 updates across our other packages. Thanks for being patient for so long 🥴

2023-01-08 01:37 UTC, rektdeckard requested changes
This looks great @micksi, thanks for taking the time to do this. Wish I had gotten to this long ago, but work and life gets in the way, and I am not a Vue dev.

Please add the `unpkg` entry back to `package.json` and delete `package-lock.json` (we are a `yarn` family 😆) and I'll merge this ASAP.

2023-01-08 01:37 UTC, rektdeckard commented on package.json
> -  "unpkg": "dist/phosphor-vue.min.js",
Please keep the `unpkg` entry, and point to the UMD bundle... I think Unpkg falls back to the `main` entry by default, but let's keep it there to be safe.

2023-01-08 01:41 UTC, rektdeckard commented
By the way, We'll be giving a lot more attention to the Phosphor libraries in the near future, have a ton of cleanup and new icons in flight. Hope to push this live within the next week or two as v2.0 (vue2) and v5.0 (vue3). As I am not myself a Vue dev, and we lost our maintainer who initially started this port, we're looking for someone interested in coming on as a maintainer if anyone is interested.

2023-02-04 11:15 UTC, dnlsndr commented
Hi there, since I've started working on the library again and there are some new icons in the pipeline, we'll soon be deploying a new major of the it. 

You can install a preview by running `npm install @phosphor-icons/vue@next`

This new version is already based on Vite 4 and takes precautions to guarantee tree-shakability (which is a big problem in the old library).

Note that it's still in alpha and is bound to change, feel free to open any issues you encounter while using the alpha library. And feel free to open any other Issues/PRs if you see something that could be done better. 
The code for the new version can be found under the `next` branch.

2023-02-04 11:15 UTC, closed without merging